version: "3"

services:

    api:
        container_name: Django
        build: 
            context: ../
            dockerfile: ./docker/dockerfile
        volumes:
            - ../app:/app
        ports:
            - 8000:8000
        tty: true